get the manifest
nomalab/deno_lib pull request #2
Opened 2022-09-23 14:12 UTC by Bramart

add getManifest function, add handleBlobRequest function specific to Blob type because of generic type errors

2022-09-23 14:28 UTC, sebcreme requested changes

2022-09-23 14:28 UTC, sebcreme commented on src/nomalab.ts
> +        undefined,
C'est moche de passer des undefined, il faut faudrait dans ce cas créer un objet option. Car là on arrive pu à lire ce que ça fait.

2022-09-23 14:28 UTC, sebcreme commented on src/nomalab.ts
> +  #handleBlobResponse(
C'est un copié coller de la méthode en dessous, il faudrait la factoriser.
le copier coller c'est pas le bienvenu ici.

2022-09-23 14:58 UTC, Bramart commented on src/nomalab.ts
> +  #handleBlobResponse(
En utilisant la fonction du dessous (handleRequest), et en ajoutant une condition pour retourner un response.blob() si jamais on traite du xml au lieu de JSON :
`// NOCONTENT
    if (response.status == 204) {
      return Promise.resolve({}) as Promise<Type>;
    } else if (response.headers.get("content-type") == "application/dash+xml") {
      return response.blob() as Promise<Type>;
    } else {
      return response.json() as Promise<Type>;
    }`

J'obtenais l'erreur suivante :
> 'Type' could be instantiated with an arbitrary type which could be unrelated to 'Blob'.deno-ts(2352)

Ca a rapport avec le type générique de la fonction, qui me retourne une erreur si on impose un type en faisant `return response.blob() as Promise<Type>;` (ici, Promise<Blob>). Je n'ai pas trouvé de solution pour corriger l'erreur, d'où la création de cette fonction qui nécessite le même traitement avec un type imposé, Blob.

2022-09-23 15:00 UTC, Bramart commented on src/nomalab.ts
> +  #handleBlobResponse(
Donc je continue de chercher pour trouver une solution au lieu de dupliquer la fonction de manière non-générique ?

2022-09-26 08:16 UTC, Bramart commented
nomalab/nomalab#4387

2022-09-29 14:35 UTC, sebcreme approved these changes

2022-09-29 15:13 UTC, merged